import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Brand & Nav
    portalTitle: 'Patient Portal',
    clinicalServices: 'Clinical Services',
    patientSpace: 'Patient Portal',
    dashboard: 'Dashboard',
    findDoctors: 'Find Doctors',
    bookVisit: 'Book Visit',
    myAppointments: 'My Appointments',
    appointments: 'Appointments',
    medicalRecords: 'Medical Records',
    myTasks: 'My Tasks',
    todoList: 'To-Do List',
    notifications: 'Notifications',
    profile: 'Profile',
    myProfile: 'My Profile',
    settings: 'Settings',
    accountSettings: 'Account Settings',
    signOut: 'Sign Out',
    support24: '24/7 Helpline',
    supportDesc: 'Immediate patient triage and support assistance.',
    welcome: 'Welcome',

    // Dashboard
    greeting: 'Hello',
    welcomeBack: "Welcome back. Here's your personal health overview, private tasks, and appointments.",
    bookNewAppointment: 'Book New Appointment',
    upcomingAppointments: 'Upcoming Appointments',
    scheduledVisits: 'Scheduled visits',
    completedAppointments: 'Completed Appointments',
    pastConsultations: 'Past consultations',
    availableDoctors: 'Available Doctors',
    accreditedSpecialists: 'Accredited specialists',
    activeTasks: 'Active Tasks',
    todoItems: 'To-Do list items',
    nextConsultation: 'Next Scheduled Consultation',
    viewDetails: 'View Details',
    cancelAppointment: 'Cancel Appointment',
    quickActions: 'Quick Actions',
    findDoctorDesc: 'Search for accredited physicians by department and specialty.',
    bookApptDesc: 'Schedule a new consultation with our 4-step wizard.',
    myApptDesc: 'View active schedules and past completed consultation history.',
    medRecordsDesc: 'Review clinical diagnoses, vital stats and doctor recommendations.',
    healthTasks: 'My Health Tasks & To-Do',
    taskTrackerFor: 'Personalized task tracker for',
    viewAll: 'View All',
    recommendedDoctors: 'Recommended Physicians for You',
    recommendedDesc: 'Top rated specialists available for consultations this week',
    exploreAll: 'Explore All',
    book: 'Book',

    // Doctors Page
    findRightDoctor: 'Find the Right Doctor',
    doctorSearchSubtitle: 'Search and choose a doctor that fits your needs.',
    searchPlaceholder: 'Search doctors by name, department, condition...',
    department: 'Department',
    specialization: 'Specialization',
    availability: 'Availability',
    experience: 'Experience',
    allDepartments: 'All Departments',
    allSpecialties: 'All Specialties',
    allAvailability: 'All Availability',
    availableToday: '🟢 Available Today',
    availableTomorrow: '🟡 Available Tomorrow',
    anyExperience: 'Any Experience',
    exp5: '5+ Years Experience',
    exp8: '8+ Years Experience',
    exp10: '10+ Years Experience',
    showingDoctors: 'Showing',
    accreditedPhysicians: 'accredited physicians',
    resetFilters: 'Reset Filters',
    noDoctorsFound: 'No doctors match your criteria',
    noDoctorsDesc: 'Try broadening your search or resetting active filters.',
    clearFilters: 'Clear All Filters',
    viewProfile: 'View Profile',
    bookAppointment: 'Book Appointment',
    consultationFee: 'Consultation Fee',
    rating: 'Rating',
    reviews: 'reviews',
    yearsExp: 'Years Exp',

    // Doctor Profile
    backToDoctors: 'Back to All Doctors',
    biography: 'Biography & Clinical Experience',
    languagesSpoken: 'Languages Spoken',
    hospitalLocation: 'Hospital Location & Wing',
    workingHours: 'Working Hours',
    availableDays: 'Available Days',
    dailySlots: 'Typical Daily Slots',
    bookWith: 'Book with',
    openDay: 'Open',
    offDay: 'Off',

    // Book Appointment
    bookWizardTitle: 'Book an Appointment',
    bookWizardSubtitle: 'Complete the 4-step wizard to reserve your consultation slot.',
    step1: 'Step 1 — Choose Your Doctor',
    step1Desc: 'Select an attending physician from our certified medical staff.',
    step2: 'Step 2 — Choose Appointment Date',
    step2Desc: 'Select your preferred date on the calendar.',
    step3: 'Step 3 — Pick Available Time Slot',
    step3Desc: 'Available morning and afternoon consultations for',
    step4: 'Step 4 — Confirm Appointment',
    step4Desc: 'Review your appointment summary and clinical consultation details.',
    step1Short: 'Select Doctor',
    step2Short: 'Choose Date',
    step3Short: 'Pick Time',
    step4Short: 'Confirm',
    proceedDate: 'Proceed to Date Selection',
    proceedTime: 'Proceed to Time Slot',
    reviewConfirm: 'Review & Confirm',
    confirmBooking: 'Confirm Appointment',
    bookingSuccess: 'Appointment Booked Successfully 🎉',
    bookingSuccessDesc: 'Your consultation request with',
    referenceId: 'Reference ID',
    viewMyAppts: 'View My Appointments',
    bookAnother: 'Book Another Visit',
    reasonPlaceholder: 'e.g. Routine checkup, blood pressure review...',
    symptomsPlaceholder: 'e.g. Occasional mild dizziness in morning...',
    reasonLabel: 'Reason for Appointment',
    symptomsLabel: 'Symptoms (Optional)',
    quickDateSuggestions: 'Quick Date Suggestions',

    // Appointments List
    myAppointmentsTitle: 'My Appointments',
    myAppointmentsSubtitle: 'Track upcoming consultations, past medical visits, and schedule status.',
    tabUpcoming: 'Upcoming',
    tabCompleted: 'Completed',
    tabCancelled: 'Cancelled',
    noUpcomingAppts: 'No upcoming appointments',
    noUpcomingDesc: 'You do not have any pending or confirmed upcoming appointments.',
    noApptsFound: 'No consultation records found.',
    cancelConfirmTitle: 'Cancel Appointment?',
    cancelConfirmDesc: 'Are you sure you want to cancel this scheduled consultation?',
    confirmCancelBtn: 'Cancel Appointment',

    // Appointment Details
    apptDetailsTitle: 'Appointment Details',
    refNumber: 'Reference Number',
    consultDate: 'Consultation Date',
    consultTime: 'Consultation Time',
    bookedOn: 'Booking Date',
    reasonForVisit: 'Reason for Visit',
    reportedSymptoms: 'Reported Symptoms',
    cancelThisAppt: 'Cancel Appointment',
    backToAppts: 'Back to Appointments',

    // Medical Records
    medRecordsTitle: 'Medical Records',
    medRecordsSubtitle: 'Educational medical records timeline with clinical diagnoses and physician recommendations.',
    medicalRecordsTitle: 'Medical History & Records',
    medicalRecordsSubtitle: 'Clinical diagnoses, vital baseline measurements, and physician recommendations.',
    addMedicalRecord: 'Add Medical Record',
    editMedicalRecord: 'Edit Medical Record',
    recordDate: 'Record Date',
    attendingDoctor: 'Attending Doctor',
    diagnosisSummary: 'Diagnosis / Clinical Summary',
    treatmentRecommendations: 'Treatment & Recommendations',
    notesAndInstructions: 'Clinical Notes & Instructions',
    deleteRecordConfirm: 'Are you sure you want to delete this medical record? This action cannot be undone.',
    noRecordsFound: 'No medical history yet',
    noRecordsDesc: 'There are no documented clinical consultation notes for your profile yet. Click "Add Medical Record" above to create one.',
    bloodPressure: 'Blood Pressure',
    optimalRange: 'Optimal Range',
    heartRate: 'Heart Rate',
    normalResting: 'Normal Resting',
    bloodSugar: 'Blood Sugar (Fasting)',
    fastingNormal: 'Fasting Normal',
    bmiWeight: 'BMI & Weight',
    healthyWeight: 'Healthy Weight',
    consultationHistory: 'Consultation History',
    eduDisclaimer: 'Educational demonstration with simulated placeholder data.',
    patientVitalsTitle: 'Patient Vitals & Health Baseline',
    restingBP: 'Resting Blood Pressure',
    avgHeartRate: 'Average Heart Rate',
    bloodGlucose: 'Blood Glucose (Fasting)',
    bloodGroupBMI: 'Blood Group & BMI',
    normalRange: 'Normal Range',
    optimal: 'Optimal',
    healthyIndex: 'Healthy Index',
    clinicalDiagnosis: 'Clinical Diagnosis',
    physicianRecommendations: 'Physician Recommendations',
    doctorClinicalNotes: 'Doctor Clinical Notes:',
    activeInCare: 'Active in-care',
    historyTimeline: 'Clinical History & Consultation Records',
    recordedConsultations: 'recorded consultations',

    // Tasks (To-Do)
    tasksTitle: 'My Tasks',
    tasksSubtitle: 'Organize your daily tasks and stay productive.',
    addNewTaskBtn: '+ Add Task',
    taskTotal: 'Total Tasks',
    taskCompleted: 'Completed',
    taskInProgress: 'In Progress',
    taskPending: 'Pending',
    allActivities: 'All scheduled activities',
    activeItems: 'Active items',
    awaitingStart: 'Awaiting start',
    filterAll: 'All',
    filterTodo: 'Todo',
    filterInProgress: 'In Progress',
    filterCompleted: 'Completed',
    filterHighPriority: 'High Priority',
    searchTasks: 'Search tasks by title, category, or note...',
    noTasksTitle: 'No tasks found',
    noTasksMatch: 'No tasks match your query.',
    deleteTaskTitle: 'Delete Task?',
    deleteTaskDesc: 'This task will be permanently removed from your personal to-do list.',
    confirmDeleteBtn: 'Delete Task',
    highPriority: 'High Priority',
    editTask: 'Edit Task',
    addNewTask: 'Add New Task',
    editTaskSubtitle: 'Update your task details and deadline',
    addTaskSubtitle: 'Organize your daily health and productivity tasks',
    taskTitle: 'Task Title',
    taskTitlePlaceholder: 'e.g., Take morning blood pressure reading',
    taskDesc: 'Description',
    taskDescPlaceholder: 'Add relevant notes, medication doses, or appointment reminders...',
    priorityLevel: 'Priority Level',
    category: 'Category',
    dueDate: 'Due Date',
    createTask: 'Create Task',
    saveChangesTask: 'Save Changes',
    categoryPersonal: 'Personal',
    categoryAppointment: 'Appointment',
    categoryStudy: 'Study',
    categoryWork: 'Work',
    categoryOther: 'Other',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',

    // Notifications
    notificationsTitle: 'Notifications',
    notificationsSubtitle: 'View appointment updates, consultation reminders, and healthcare alerts.',
    markAllRead: 'Mark all read',
    allNotifications: 'All Notifications',
    unread: 'Unread',
    noNotifsTitle: 'No notifications found',
    noNotifsDesc: 'You have caught up with all active alerts.',

    // Profile & Settings
    profileTitle: 'Patient Profile',
    editProfile: 'Edit Profile',
    patientMember: 'Patient Member',
    roleAdmin: 'Administrator',
    roleDoctor: 'Doctor',
    rolePatient: 'Patient Member',
    adminBio: 'MediCare system administrator.',
    doctorBio: 'MediCare certified physician.',
    patientBio: 'MediCare verified patient member.',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    homeAddress: 'Home Address',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    emergencyContact: 'Emergency Contact',
    saveChanges: 'Save Changes',
    saveInfo: 'Save Information',
    security: 'Security',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    preferences: 'Preferences',
    interfaceTheme: 'Interface Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    preferredLanguage: 'Preferred Language',
    savePreferences: 'Save Preferences',

    // Common
    open: 'Open',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    confirm: 'Confirm',
    action: 'Action',
    edit: 'Edit',
    delete: 'Delete',
    addNew: 'Add New',
    search: 'Search',

    // Admin & Management
    adminPortal: 'Admin Portal',
    adminDashboard: 'Admin Dashboard',
    hospitalStats: 'Hospital Performance & Metrics',
    manageDoctors: 'Manage Doctors',
    managePatients: 'Manage Patients',
    allAppointments: 'All Appointments',
    addDoctor: 'Add Doctor',
    addPatient: 'Add Patient',
    editDoctor: 'Edit Doctor Details',
    editPatient: 'Edit Patient Details',
    deleteDoctorConfirm: 'Are you sure you want to remove this doctor from the hospital staff?',
    deletePatientConfirm: 'Are you sure you want to delete this patient record?',
    totalPatients: 'Total Patients',
    totalDoctors: 'Total Doctors',
    pendingAppointments: 'Pending Appointments',
    patients: 'Patients',
    doctors: 'Doctors',
    medicalCondition: 'Medical Condition',
    doctorName: 'Doctor Name',
    patientName: 'Patient Name',
    educationDegree: 'Education & Credentials',
    searchPatients: 'Search patients by name, email, phone...',
    searchDoctors: 'Search doctors by name, specialty, department...',
    registeredDate: 'Enrolled Date',
    allStatuses: 'All Statuses'
  },

  uz: {
    // Brand & Nav
    portalTitle: 'Bemor Portali',
    clinicalServices: 'Klinik Xizmatlar',
    patientSpace: 'Bemor Maydoni',
    dashboard: 'Bosh sahifa',
    findDoctors: 'Shifokorlar',
    bookVisit: 'Qabulga yozilish',
    myAppointments: 'Mening qabullarim',
    appointments: 'Qabullar',
    medicalRecords: 'Tibbiy tarix',
    myTasks: 'Mening vazifalarim',
    todoList: 'Vazifalar (To-Do)',
    notifications: 'Bildirishnomalar',
    profile: 'Profil',
    myProfile: 'Mening profilim',
    settings: 'Sozlamalar',
    accountSettings: 'Hisob sozlamalari',
    signOut: 'Chiqish',
    support24: '24/7 Tezkor Yordam',
    supportDesc: 'Bemorlarga kechayu-kunduz tezkor tibbiy maslahat va yordam.',
    welcome: 'Xush kelibsiz',

    // Dashboard
    greeting: 'Assalomu alaykum',
    welcomeBack: "Xush kelibsiz. Bu yerda sizning shaxsiy tibbiy ko'rsatkichlaringiz, vazifalar va qabullaringiz jamlangan.",
    bookNewAppointment: 'Yangi qabulga yozilish',
    upcomingAppointments: 'Kutilayotgan qabullar',
    scheduledVisits: 'Rejalashtirilgan tashriflar',
    completedAppointments: 'Bajarilgan qabullar',
    pastConsultations: "O'tgan konsultatsiyalar",
    availableDoctors: 'Mavjud shifokorlar',
    accreditedSpecialists: 'Malakali mutaxassislar',
    activeTasks: 'Faol vazifalar',
    todoItems: "To-Do ro'yxatidagi vazifalar",
    nextConsultation: 'Navbatdagi Rejalashtirilgan Qabul',
    viewDetails: "Batafsil ko'rish",
    cancelAppointment: 'Qabulni bekor qilish',
    quickActions: 'Tezkor Amallar',
    findDoctorDesc: "Bo'lim va ixtisoslik bo'yicha eng yaxshi shifokorlarni toping.",
    bookApptDesc: '4 bosqichli qulay usta orqali qabulga yoziling.',
    myApptDesc: 'Faol va oldingi shifokor qabullaringizni kuzatib boring.',
    medRecordsDesc: 'Tashxislar, tahlillar va shifokor tavsiyalarini tekshiring.',
    healthTasks: 'Mening Salomatlik Vazifalarim',
    taskTrackerFor: 'uchun shaxsiy vazifalar nazorati',
    viewAll: "Barchasini ko'rish",
    recommendedDoctors: 'Siz uchun Tavsiya Etilgan Shifokorlar',
    recommendedDesc: 'Ushbu haftada qabulga tayyor yuqori reytingli mutaxassislar',
    exploreAll: "Barcha shifokorlar",
    book: 'Yozilish',

    // Doctors Page
    findRightDoctor: "Kerakli Shifokorni Toping",
    doctorSearchSubtitle: "O'zingizga mos shifokorni izlang va tanlang.",
    searchPlaceholder: "Shifokorlarni ismi, bo'limi, tashxis bo'yicha qidiring...",
    department: "Bo'lim",
    specialization: 'Ixtisoslik',
    availability: 'Mavjudlik',
    experience: 'Tajriba',
    allDepartments: "Barcha bo'limlar",
    allSpecialties: 'Barcha mutaxassisliklar',
    allAvailability: 'Barcha holatlar',
    availableToday: '🟢 Bugun qabul bor',
    availableTomorrow: '🟡 Ertaga qabul bor',
    anyExperience: 'Ixtiyoriy tajriba',
    exp5: '5+ Yillik Tajriba',
    exp8: '8+ Yillik Tajriba',
    exp10: '10+ Yillik Tajriba',
    showingDoctors: "Ko'rsatilmoqda",
    accreditedPhysicians: 'nafar malakali shifokor',
    resetFilters: 'Filtrlarni tozalash',
    noDoctorsFound: 'Mos keluvchi shifokorlar topilmadi',
    noDoctorsDesc: "Qidiruv parametrlarini o'zgartirib yoki filtrlarni tozalab ko'ring.",
    clearFilters: 'Barcha filtrlarni tozalash',
    viewProfile: "Profilni ko'rish",
    bookAppointment: 'Qabulga yozilish',
    consultationFee: 'Konsultatsiya narxi',
    rating: 'Reyting',
    reviews: 'sharhlar',
    yearsExp: 'Yillik tajriba',

    // Doctor Profile
    backToDoctors: 'Barcha shifokorlarga qaytish',
    biography: 'Biografiya va Klinik Tajriba',
    languagesSpoken: 'Muloqot tillari',
    hospitalLocation: 'Shifoxona manzili va binosi',
    workingHours: 'Ish vaqti',
    availableDays: 'Qabul kunlari',
    dailySlots: 'Kunlik qabul vaqtlari',
    bookWith: 'Shifokor qabuliga yozilish',
    openDay: 'Ochiq',
    offDay: 'Dam olish',

    // Book Appointment
    bookWizardTitle: 'Qabulga Yozilish',
    bookWizardSubtitle: 'Konsultatsiya vaqtini band qilish uchun 4 bosqichni bajaring.',
    step1: '1-Bosqich — Shifokorni Tanlang',
    step1Desc: 'Malakali tibbiyot xodimlarimiz orasidan shifokorni tanlang.',
    step2: '2-Bosqich — Sanani Tanlang',
    step2Desc: 'Taqvimdan qulay sanani tanlang.',
    step3: '3-Bosqich — Bo‘sh Vaqtni Tanlang',
    step3Desc: 'Ushbu sana uchun mavjud konsultatsiya vaqtlari:',
    step4: '4-Bosqich — Qabulni Tasdiqlash',
    step4Desc: 'Qabul xulosasi va konsultatsiya tafsilotlarini tekshiring.',
    step1Short: 'Shifokor',
    step2Short: 'Sana',
    step3Short: 'Vaqt',
    step4Short: 'Tasdiqlash',
    proceedDate: 'Sana tanlashga o‘tish',
    proceedTime: 'Vaqt tanlashga o‘tish',
    reviewConfirm: 'Tekshirish va Tasdiqlash',
    confirmBooking: 'Qabulni Tasdiqlash',
    bookingSuccess: 'Qabul Muvaffaqiyatli Band Qilindi 🎉',
    bookingSuccessDesc: 'Shifokor qabuliga yuborilgan so‘rovingiz tasdiqlandi:',
    referenceId: 'Buyurtma ID',
    viewMyAppts: 'Qabullarimni Ko‘rish',
    bookAnother: 'Yana Qabulga Yozilish',
    reasonPlaceholder: 'masalan: Rejali ko‘rik, qon bosimi tekshiruvi...',
    symptomsPlaceholder: 'masalan: Ertalabki bosh aylanishi...',
    reasonLabel: 'Tashrif sababi',
    symptomsLabel: 'Shikoyat va belgilar (ixtiyoriy)',
    quickDateSuggestions: 'Tezkor sana tavsiyalari',

    // Appointments List
    myAppointmentsTitle: 'Mening Qabullarim',
    myAppointmentsSubtitle: 'Kutilayotgan tashriflar, o‘tgan qabullar va holatlarni kuzating.',
    tabUpcoming: 'Kutilayotgan',
    tabCompleted: 'Bajarilgan',
    tabCancelled: 'Bekor qilingan',
    noUpcomingAppts: 'Kutilayotgan qabullar yo‘q',
    noUpcomingDesc: 'Sizda hozircha faol yoki kutilayotgan qabullar mavjud emas.',
    noApptsFound: 'Konsultatsiya yozuvlari topilmadi.',
    cancelConfirmTitle: 'Qabulni bekor qilmoqchimisiz?',
    cancelConfirmDesc: 'Ushbu rejalashtirilgan qabulni bekor qilishga ishonchingiz komilmi?',
    confirmCancelBtn: 'Qabulni bekor qilish',

    // Appointment Details
    apptDetailsTitle: 'Qabul Tafsilotlari',
    refNumber: 'Raqam ID',
    consultDate: 'Qabul sanasi',
    consultTime: 'Qabul vaqti',
    bookedOn: 'Band qilingan sana',
    reasonForVisit: 'Tashrif sababi',
    reportedSymptoms: 'Keltirilgan belgilar',
    cancelThisAppt: 'Qabulni bekor qilish',
    backToAppts: 'Qabullarga qaytish',

    // Medical Records
    medRecordsTitle: 'Tibbiy Tarix (Medkarta)',
    medRecordsSubtitle: 'Klinik tashxislar, tahlillar va shifokor tavsiyalari xronologiyasi.',
    medicalRecordsTitle: 'Tibbiy Tarix va Xulosalar',
    medicalRecordsSubtitle: 'Klinik tashxislar, hayotiy ko‘rsatkichlar va shifokor tavsiyalari xronologiyasi.',
    addMedicalRecord: 'Yangi yozuv qo‘shish',
    editMedicalRecord: 'Tibbiy xulosani tahrirlash',
    recordDate: 'Sana',
    attendingDoctor: 'Shifokor',
    diagnosisSummary: 'Tashxis / Klinik xulosa',
    treatmentRecommendations: 'Tavsiyalar va Muolajalar',
    notesAndInstructions: 'Qo‘shimcha ko‘rsatmalar',
    deleteRecordConfirm: 'Ushbu tibbiy xulosani o‘chirib tashlamoqchimisiz? Ushbu amalni qaytarib bo‘lmaydi.',
    noRecordsFound: 'Tibbiy yozuvlar topilmadi',
    noRecordsDesc: 'Hozircha sizning profilingizda qayd etilgan tibbiy xulosalar mavjud emas. Yuqoridagi tugma orqali yangi yozuv qo‘shishingiz mumkin.',
    bloodPressure: 'Qon Bosimi',
    optimalRange: 'Optimal Me’yorda',
    heartRate: 'Yurak Urishi',
    normalResting: 'Tinch Holatda Me’yorda',
    bloodSugar: 'Qondagi Qand',
    fastingNormal: 'Och Qoringa Me’yorda',
    bmiWeight: 'Tana Massasi Indeksi (BMI)',
    healthyWeight: 'Sog‘lom Vazn',
    consultationHistory: 'Konsultatsiyalar Tarixi',
    eduDisclaimer: 'Simulyatsiya qilingan maʼlumotlar asosidagi portfolio ko‘rgazmasi.',
    patientVitalsTitle: 'Bemor Hayotiy Ko‘rsatkichlari (Vitals)',
    restingBP: 'Tinch Holatdagi Qon Bosimi',
    avgHeartRate: 'O‘rtacha Yurak Urishi',
    bloodGlucose: 'Qondagi Qand Miqdori',
    bloodGroupBMI: 'Qon Guruhi va BMI',
    normalRange: 'Normal Meʼyorda',
    optimal: 'Optimal',
    healthyIndex: 'Sog‘lom Ko‘rsatkich',
    clinicalDiagnosis: 'Klinik Tashxis',
    physicianRecommendations: 'Shifokor Tavsiyalari',
    doctorClinicalNotes: 'Shifokorning Klinik Qaydlari:',
    activeInCare: 'Nazorat ostida',
    historyTimeline: 'Klinik Tarix va Konsultatsiyalar',
    recordedConsultations: 'ta qayd etilgan konsultatsiya',

    // Tasks (To-Do)
    tasksTitle: 'Mening Vazifalarim',
    tasksSubtitle: 'Kunlik sog‘lomlashtirish vazifalaringizni tartibga soling.',
    addNewTaskBtn: '+ Vazifa Qo‘shish',
    taskTotal: 'Jami Vazifalar',
    taskCompleted: 'Bajarildi',
    taskInProgress: 'Jarayonda',
    taskPending: 'Kutilmoqda',
    allActivities: 'Barcha rejalashtirilgan ishlar',
    activeItems: 'Faol vazifalar',
    awaitingStart: 'Boshlanishi kutilmoqda',
    filterAll: 'Barchasi',
    filterTodo: 'Bajarish kerak',
    filterInProgress: 'Jarayonda',
    filterCompleted: 'Bajarildi',
    filterHighPriority: 'Yuqori Muhimlik',
    searchTasks: 'Vazifalarni sarlavha, toifa yoki eslatma bo‘yicha qidirish...',
    noTasksTitle: 'Vazifalar topilmadi',
    noTasksMatch: 'Qidiruvingizga mos vazifalar mavjud emas.',
    deleteTaskTitle: 'Vazifani o‘chirmoqchimisiz?',
    deleteTaskDesc: 'Ushbu vazifa ro‘yxatingizdan butunlay olib tashlanadi.',
    confirmDeleteBtn: 'Vazifani o‘chirish',
    highPriority: 'Yuqori Muhimlik',
    editTask: 'Vazifani Tahrirlash',
    addNewTask: 'Yangi Vazifa Qo‘shish',
    editTaskSubtitle: 'Vazifa maʼlumotlari va muddatini yangilang',
    addTaskSubtitle: 'Kunlik salomatlik va rejalaringizni tartibga soling',
    taskTitle: 'Vazifa Sarlavhasi',
    taskTitlePlaceholder: 'masalan: Ertalabki qon bosimini o‘lchash',
    taskDesc: 'Tavsif / Izoh',
    taskDescPlaceholder: 'Kerakli eslatmalar, dori dozalari yoki tavsiyalarni yozing...',
    priorityLevel: 'Muhimlik Darajasi',
    category: 'Kategoriya',
    dueDate: 'Bajarish Sanasi',
    createTask: 'Vazifa Yaratish',
    saveChangesTask: 'O‘zgarishlarni Saqlash',
    categoryPersonal: 'Shaxsiy',
    categoryAppointment: 'Qabul / Shifokor',
    categoryStudy: 'O‘qish',
    categoryWork: 'Ish',
    categoryOther: 'Boshqa',
    priorityLow: 'Past',
    priorityMedium: 'O‘rta',
    priorityHigh: 'Yuqori',

    // Notifications
    notificationsTitle: 'Bildirishnomalar',
    notificationsSubtitle: 'Qabul yangilanishlari, eslatmalar va tibbiy xabarlar.',
    markAllRead: 'Barchasini o‘qilgan qilish',
    allNotifications: 'Barcha bildirishnomalar',
    unread: 'O‘qilmagan',
    noNotifsTitle: 'Bildirishnomalar yo‘q',
    noNotifsDesc: 'Barcha faol xabarlar bilan tanishib bo‘lgansiz.',

    // Profile & Settings
    profileTitle: 'Bemor Profili',
    editProfile: 'Profilni tahrirlash',
    patientMember: 'Aʼzo Bemor',
    roleAdmin: 'Administrator',
    roleDoctor: 'Shifokor',
    rolePatient: 'Aʼzo Bemor',
    adminBio: 'MediCare tizim boshqaruvchisi va administratori.',
    doctorBio: 'MediCare malakali shifokor mutaxassisi.',
    patientBio: 'MediCare ro‘yxatdan o‘tgan bemor aʼzosi.',
    personalInfo: 'Shaxsiy Maʼlumotlar',
    fullName: 'To‘liq Ism Familiya',
    emailAddress: 'Email Manzil',
    phoneNumber: 'Telefon Raqam',
    homeAddress: 'Yashash Manzili',
    dateOfBirth: 'Tug‘ilgan Sana',
    gender: 'Jins',
    bloodGroup: 'Qon Guruhi',
    emergencyContact: 'Favqulodda Aloqa',
    saveChanges: 'O‘zgarishlarni Saqlash',
    saveInfo: 'Maʼlumotlarni Saqlash',
    security: 'Xavfsizlik',
    changePassword: 'Parolni O‘zgartirish',
    currentPassword: 'Amaldagi Parol',
    newPassword: 'Yangi Parol',
    confirmNewPassword: 'Yangi Parolni Tasdiqlang',
    updatePassword: 'Parolni Yangilash',
    preferences: 'Sozlamalar va Ko‘rinish',
    interfaceTheme: 'Interfeys Mavzusi',
    lightMode: 'Yorug‘ Rejim (Light)',
    darkMode: 'Tungi Rejim (Dark)',
    preferredLanguage: 'Dastur Tili',
    savePreferences: 'Sozlamalarni Saqlash',

    // Common
    open: 'Ochish',
    status: 'Holat',
    date: 'Sana',
    time: 'Vaqt',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    back: 'Orqaga',
    confirm: 'Tasdiqlash',
    action: 'Amal',
    edit: 'Tahrirlash',
    delete: 'O‘chirish',
    addNew: 'Yangi qo‘shish',
    search: 'Qidirish',

    // Admin & Management
    adminPortal: 'Admin Paneli',
    adminDashboard: 'Admin Boshqaruv Paneli',
    hospitalStats: 'Kasalxona Umumiy Ko‘rsatkichlari',
    manageDoctors: 'Shifokorlarni Boshqarish',
    managePatients: 'Bemorlarni Boshqarish',
    allAppointments: 'Barcha Qabullar',
    addDoctor: 'Shifokor Qo‘shish',
    addPatient: 'Bemor Qo‘shish',
    editDoctor: 'Shifokorni Tahrirlash',
    editPatient: 'Bemorni Tahrirlash',
    deleteDoctorConfirm: 'Haqiqatan ham bu shifokorni xodimlar safidan o‘chirmoqchimisiz?',
    deletePatientConfirm: 'Haqiqatan ham ushbu bemor kartasini o‘chirmoqchimisiz?',
    totalPatients: 'Jami Bemorlar',
    totalDoctors: 'Jami Shifokorlar',
    pendingAppointments: 'Kutilayotgan Qabullar',
    patients: 'Bemorlar',
    doctors: 'Shifokorlar',
    medicalCondition: 'Tibbiy Tashxis / Holat',
    doctorName: 'Shifokor Ismi',
    patientName: 'Bemor Ismi',
    educationDegree: 'Ta‘limi va Mutaxassisligi',
    searchPatients: 'Bemorlarni ismi, telefoni, emaili bo‘yicha qidirish...',
    searchDoctors: 'Shifokorlarni ismi, bo‘limi, mutaxassisligi bo‘yicha qidirish...',
    registeredDate: 'Ro‘yxatdan o‘tgan sana',
    allStatuses: 'Barcha holatlar'
  },

  ru: {
    // Brand & Nav
    portalTitle: 'Портал Пациента',
    clinicalServices: 'Клинические Услуги',
    patientSpace: 'Пространство Пациента',
    dashboard: 'Главная панель',
    findDoctors: 'Поиск Врачей',
    bookVisit: 'Запись на прием',
    myAppointments: 'Мои Записи',
    appointments: 'Записи',
    medicalRecords: 'Медкарта',
    myTasks: 'Мои Задачи',
    todoList: 'Список Задач',
    notifications: 'Уведомления',
    profile: 'Профиль',
    myProfile: 'Мой Профиль',
    settings: 'Настройки',
    accountSettings: 'Настройки Аккаунта',
    signOut: 'Выйти',
    support24: 'Поддержка 24/7',
    supportDesc: 'Круглосуточная медицинская помощь и консультации.',
    welcome: 'Добро пожаловать',

    // Dashboard
    greeting: 'Здравствуйте',
    welcomeBack: 'Добро пожаловать. Ваш персональный медицинский обзор, задачи и записи к врачам.',
    bookNewAppointment: 'Записаться на прием',
    upcomingAppointments: 'Предстоящие приемы',
    scheduledVisits: 'Запланированные визиты',
    completedAppointments: 'Завершенные приемы',
    pastConsultations: 'Прошедшие консультации',
    availableDoctors: 'Доступные Врачи',
    accreditedSpecialists: 'Квалифицированные специалисты',
    activeTasks: 'Активные Задачи',
    todoItems: 'Элементов в списке задач',
    nextConsultation: 'Ближайшая Консультация',
    viewDetails: 'Подробнее',
    cancelAppointment: 'Отменить прием',
    quickActions: 'Быстрые Действия',
    findDoctorDesc: 'Поиск сертифицированных врачей по отделениям и специальностям.',
    bookApptDesc: 'Удобная запись на консультацию за 4 простых шага.',
    myApptDesc: 'Просмотр активных записей и истории завершенных визитов.',
    medRecordsDesc: 'Просмотр клинических диагнозов, показателей и рекомендаций.',
    healthTasks: 'Мои Задачи по Здоровью',
    taskTrackerFor: 'Персональный список задач для',
    viewAll: 'Смотреть все',
    recommendedDoctors: 'Рекомендуемые Врачи',
    recommendedDesc: 'Лучшие специалисты, доступные для приема на этой неделе',
    exploreAll: 'Все врачи',
    book: 'Записаться',

    // Doctors Page
    findRightDoctor: 'Найдите Подходящего Врача',
    doctorSearchSubtitle: 'Поиск и выбор специалиста под ваши потребности.',
    searchPlaceholder: 'Поиск врачей по имени, отделению, диагнозу...',
    department: 'Отделение',
    specialization: 'Специальность',
    availability: 'Доступность',
    experience: 'Опыт работы',
    allDepartments: 'Все отделения',
    allSpecialties: 'Все специальности',
    allAvailability: 'Любая доступность',
    availableToday: '🟢 Доступен сегодня',
    availableTomorrow: '🟡 Доступен завтра',
    anyExperience: 'Любой стаж',
    exp5: 'Опыт от 5 лет',
    exp8: 'Опыт от 8 лет',
    exp10: 'Опыт от 10 лет',
    showingDoctors: 'Показано',
    accreditedPhysicians: 'аккредитованных врачей',
    resetFilters: 'Сбросить фильтры',
    noDoctorsFound: 'Врачи по вашему запросу не найдены',
    noDoctorsDesc: 'Попробуйте изменить параметры поиска или сбросить фильтры.',
    clearFilters: 'Сбросить все фильтры',
    viewProfile: 'Профиль врача',
    bookAppointment: 'Записаться',
    consultationFee: 'Стоимость приема',
    rating: 'Рейтинг',
    reviews: 'отзывов',
    yearsExp: 'Опыт работы',

    // Doctor Profile
    backToDoctors: 'Назад ко всем врачам',
    biography: 'Биография и Клинический Опыт',
    languagesSpoken: 'Языки приема',
    hospitalLocation: 'Корпус и отделение больницы',
    workingHours: 'Часы приема',
    availableDays: 'Дни приема',
    dailySlots: 'Доступное время в течение дня',
    bookWith: 'Записаться к врачу',
    openDay: 'Прием есть',
    offDay: 'Выходной',

    // Book Appointment
    bookWizardTitle: 'Запись на Прием',
    bookWizardSubtitle: 'Пройдите 4 простых шага, чтобы забронировать время приема.',
    step1: 'Шаг 1 — Выберите Врача',
    step1Desc: 'Выберите нужного специалиста из сертифицированного штата врачей.',
    step2: 'Шаг 2 — Выберите Дату Приема',
    step2Desc: 'Выберите удобную дату в календаре.',
    step3: 'Шаг 3 — Выберите Время Приема',
    step3Desc: 'Доступное время консультаций на выбранную дату:',
    step4: 'Шаг 4 — Подтверждение Записи',
    step4Desc: 'Проверьте данные записи и детали консультации.',
    step1Short: 'Врач',
    step2Short: 'Дата',
    step3Short: 'Время',
    step4Short: 'Подтвердить',
    proceedDate: 'Перейти к выбору даты',
    proceedTime: 'Перейти к выбору времени',
    reviewConfirm: 'Проверить и Подтвердить',
    confirmBooking: 'Подтвердить Запись',
    bookingSuccess: 'Запись Успешно Оформлена 🎉',
    bookingSuccessDesc: 'Ваш запрос на консультацию успешно отправлен:',
    referenceId: 'Номер брони',
    viewMyAppts: 'Мои Записи',
    bookAnother: 'Записаться еще раз',
    reasonPlaceholder: 'напр.: Плановый осмотр, контроль давления...',
    symptomsPlaceholder: 'напр.: Головокружение по утрам...',
    reasonLabel: 'Причина визита',
    symptomsLabel: 'Симптомы (необязательно)',
    quickDateSuggestions: 'Быстрый выбор даты',

    // Appointments List
    myAppointmentsTitle: 'Мои Записи на Прием',
    myAppointmentsSubtitle: 'Отслеживайте предстоящие визиты, историю консультаций и статусы.',
    tabUpcoming: 'Предстоящие',
    tabCompleted: 'Завершенные',
    tabCancelled: 'Отмененные',
    noUpcomingAppts: 'Нет предстоящих записей',
    noUpcomingDesc: 'У вас нет активных запланированных приемов к врачу.',
    noApptsFound: 'Записи консультаций не найдены.',
    cancelConfirmTitle: 'Отменить запись?',
    cancelConfirmDesc: 'Вы уверены, что хотите отменить эту запись на прием?',
    confirmCancelBtn: 'Отменить запись',

    // Appointment Details
    apptDetailsTitle: 'Детали Записи',
    refNumber: 'Номер записи',
    consultDate: 'Дата консультации',
    consultTime: 'Время консультации',
    bookedOn: 'Дата оформления',
    reasonForVisit: 'Причина обращения',
    reportedSymptoms: 'Указанные симптомы',
    cancelThisAppt: 'Отменить запись',
    backToAppts: 'Назад к записям',

    // Medical Records
    medRecordsTitle: 'Медицинская Карта',
    medRecordsSubtitle: 'История клинических диагнозов, показателей и рекомендаций врачей.',
    medicalRecordsTitle: 'Медицинская История и Карты',
    medicalRecordsSubtitle: 'Хронология клинических диагнозов, жизненных показателей и рекомендаций врачей.',
    addMedicalRecord: 'Добавить запись',
    editMedicalRecord: 'Редактировать запись',
    recordDate: 'Дата записи',
    attendingDoctor: 'Лечащий врач',
    diagnosisSummary: 'Диагноз / Клиническое заключение',
    treatmentRecommendations: 'Рекомендации и Лечение',
    notesAndInstructions: 'Клинические заметки и инструкции',
    deleteRecordConfirm: 'Вы уверены, что хотите удалить эту медицинскую запись? Это действие нельзя отменить.',
    noRecordsFound: 'Медицинские записи не найдены',
    noRecordsDesc: 'В вашем профиле пока нет зафиксированных клинических заключений. Нажмите «Добавить запись» выше, чтобы создать новую.',
    bloodPressure: 'Артериальное Давление',
    optimalRange: 'Оптимальная норма',
    heartRate: 'Пульс',
    normalResting: 'В покое норма',
    bloodSugar: 'Сахар в Крови',
    fastingNormal: 'Натощак норма',
    bmiWeight: 'Индекс Массы Тела (ИМТ)',
    healthyWeight: 'Здоровый вес',
    consultationHistory: 'История Консультаций',
    eduDisclaimer: 'Учебная демонстрация с симулированными данными.',
    patientVitalsTitle: 'Жизненные Показатели Пациента (Vitals)',
    restingBP: 'Артериальное Давление в Покое',
    avgHeartRate: 'Средний Пульс',
    bloodGlucose: 'Глюкоза в Крови (натощак)',
    bloodGroupBMI: 'Группа Крови и ИМТ',
    normalRange: 'В пределах нормы',
    optimal: 'Оптимально',
    healthyIndex: 'Здоровый показатель',
    clinicalDiagnosis: 'Клинический Диагноз',
    physicianRecommendations: 'Рекомендации Врача',
    doctorClinicalNotes: 'Клинические Заметки Врача:',
    activeInCare: 'Под наблюдением',
    historyTimeline: 'Клиническая История и Консультации',
    recordedConsultations: 'зафиксированных консультаций',

    // Tasks (To-Do)
    tasksTitle: 'Мои Задачи',
    tasksSubtitle: 'Организуйте задачи по здоровью и оставайтесь продуктивными.',
    addNewTaskBtn: '+ Добавить Задачу',
    taskTotal: 'Всего Задач',
    taskCompleted: 'Выполнено',
    taskInProgress: 'В процессе',
    taskPending: 'Ожидает',
    allActivities: 'Все запланированные дела',
    activeItems: 'Активные задачи',
    awaitingStart: 'Ожидает начала',
    filterAll: 'Все',
    filterTodo: 'Сделать',
    filterInProgress: 'В процессе',
    filterCompleted: 'Выполнено',
    filterHighPriority: 'Высокий Приоритет',
    searchTasks: 'Поиск задач по названию, категории или заметке...',
    noTasksTitle: 'Задачи не найдены',
    noTasksMatch: 'Задачи по вашему запросу отсутствуют.',
    deleteTaskTitle: 'Удалить задачу?',
    deleteTaskDesc: 'Эта задача будет безвозвратно удалена из вашего списка.',
    confirmDeleteBtn: 'Удалить задачу',
    highPriority: 'Высокий Приоритет',
    editTask: 'Редактировать Задачу',
    addNewTask: 'Добавить Новую Задачу',
    editTaskSubtitle: 'Обновите детали задачи и срок выполнения',
    addTaskSubtitle: 'Организуйте задачи по здоровью и продуктивности',
    taskTitle: 'Название Задачи',
    taskTitlePlaceholder: 'напр.: Утреннее измерение артериального давления',
    taskDesc: 'Описание',
    taskDescPlaceholder: 'Добавьте заметки, дозировку лекарств или напоминания...',
    priorityLevel: 'Приоритет',
    category: 'Категория',
    dueDate: 'Срок Выполнения',
    createTask: 'Создать Задачу',
    saveChangesTask: 'Сохранить Изменения',
    categoryPersonal: 'Личное',
    categoryAppointment: 'Прием / Врач',
    categoryStudy: 'Учеба',
    categoryWork: 'Работа',
    categoryOther: 'Другое',
    priorityLow: 'Низкий',
    priorityMedium: 'Средний',
    priorityHigh: 'Высокий',

    // Notifications
    notificationsTitle: 'Уведомления',
    notificationsSubtitle: 'Обновления записей, напоминания о приеме и медицинские оповещения.',
    markAllRead: 'Прочитать все',
    allNotifications: 'Все уведомления',
    unread: 'Непрочитанные',
    noNotifsTitle: 'Уведомлений нет',
    noNotifsDesc: 'Вы ознакомились со всеми активными уведомлениями.',

    // Profile & Settings
    profileTitle: 'Профиль Пользователя',
    editProfile: 'Редактировать Профиль',
    patientMember: 'Зарегистрированный Пациент',
    roleAdmin: 'Администратор',
    roleDoctor: 'Врач',
    rolePatient: 'Пациент',
    adminBio: 'Системный администратор платформы MediCare.',
    doctorBio: 'Квалифицированный врач MediCare.',
    patientBio: 'Зарегистрированный пациент MediCare.',
    personalInfo: 'Личная Информация',
    fullName: 'Полное Имя',
    emailAddress: 'Электронная Почта',
    phoneNumber: 'Номер Телефона',
    homeAddress: 'Домашний Адрес',
    dateOfBirth: 'Дата Рождения',
    gender: 'Пол',
    bloodGroup: 'Группа Крови',
    emergencyContact: 'Экстренный Контакт',
    saveChanges: 'Сохранить Изменения',
    saveInfo: 'Сохранить Данные',
    security: 'Безопасность',
    changePassword: 'Смена Пароля',
    currentPassword: 'Текущий Пароль',
    newPassword: 'Новый Пароль',
    confirmNewPassword: 'Подтвердите Новый Пароль',
    updatePassword: 'Обновить Пароль',
    preferences: 'Настройки и Оформление',
    interfaceTheme: 'Тема Интерфейса',
    lightMode: 'Светлая Тема (Light)',
    darkMode: 'Темная Тема (Dark)',
    preferredLanguage: 'Язык Интерфейса',
    savePreferences: 'Сохранить Настройки',

    // Common
    open: 'Открыть',
    status: 'Статус',
    date: 'Дата',
    time: 'Время',
    save: 'Сохранить',
    cancel: 'Отмена',
    back: 'Назад',
    confirm: 'Подтвердить',
    action: 'Действие',
    edit: 'Редактировать',
    delete: 'Удалить',
    addNew: 'Добавить',
    search: 'Поиск',

    // Admin & Management
    adminPortal: 'Панель Администратора',
    adminDashboard: 'Панель Управления',
    hospitalStats: 'Статистика и Показатели Больницы',
    manageDoctors: 'Управление Врачами',
    managePatients: 'Управление Пациентами',
    allAppointments: 'Все Записи',
    addDoctor: 'Добавить Врача',
    addPatient: 'Добавить Пациента',
    editDoctor: 'Редактировать Врача',
    editPatient: 'Редактировать Пациента',
    deleteDoctorConfirm: 'Вы уверены, что хотите удалить этого врача из штата?',
    deletePatientConfirm: 'Вы уверены, что хотите удалить карту этого пациента?',
    totalPatients: 'Всего Пациентов',
    totalDoctors: 'Всего Врачей',
    pendingAppointments: 'Ожидающие Приемы',
    patients: 'Пациенты',
    doctors: 'Врачи',
    medicalCondition: 'Медицинское Состояние',
    doctorName: 'Имя Врача',
    patientName: 'Имя Пациента',
    educationDegree: 'Образование и Квалификация',
    searchPatients: 'Поиск пациентов по имени, телефону, email...',
    searchDoctors: 'Поиск врачей по имени, отделению, специальности...',
    registeredDate: 'Дата Регистрации',
    allStatuses: 'Все статусы'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('medicare_lang') || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('medicare_lang', lang);
  }, [lang]);

  const t = (key) => {
    const currentDict = translations[lang] || translations.uz;
    return currentDict[key] || translations.en[key] || key;
  };

  const languagesList = [
    { code: 'uz', name: 'O‘zbekcha', flag: '🇺🇿' },
    { code: 'ru', name: 'Русский', flag: '🇷🇺' },
    { code: 'en', name: 'English', flag: '🇬🇧' }
  ];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languagesList }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
